receivers:
  k8s_cluster:
    node_conditions_to_report:
      - Ready
      - DiskPressure
      - MemoryPressure
      - PIDPressure
      - NetworkUnavailable

  kubeletstats:
    auth_type: "serviceAccount"
    endpoint: "${K8S_NODE_NAME}:10250"
    insecure_skip_verify: true
    extra_metadata_labels:
      - container.id
      - k8s.volume.type
    k8s_api_config:
      auth_type: serviceAccount

processors:
  memory_limiter:
    ballast_size_mib: 33
    limit_mib: 160
    spike_limit_mib: 50
    check_interval: 5s
  batch:

exporters:
  # logging:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check: {}

service:
  extensions:
    - health_check
  pipelines:
    metrics:
      receivers:
        # - hostmetrics
        # - k8s_cluster
        - kubeletstats
      processors:
        - memory_limiter
        - batch
      exporters:
        - logging
        # - prometheus
